export default {
    "login": "noe-ps",
    "id": 52591813,
    "node_id": "MDQ6VXNlcjUyNTkxODEz",
    "avatar_url": "https://avatars.githubusercontent.com/u/52591813?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/noe-ps",
    "html_url": "https://github.com/noe-ps",
    "followers_url": "https://api.github.com/users/noe-ps/followers",
    "following_url": "https://api.github.com/users/noe-ps/following{/other_user}",
    "gists_url": "https://api.github.com/users/noe-ps/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/noe-ps/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/noe-ps/subscriptions",
    "organizations_url": "https://api.github.com/users/noe-ps/orgs",
    "repos_url": "https://api.github.com/users/noe-ps/repos",
    "events_url": "https://api.github.com/users/noe-ps/events{/privacy}",
    "received_events_url": "https://api.github.com/users/noe-ps/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Noe Ps",
    "company": null,
    "blog": "",
    "location": "Mexico CDMX",
    "email": null,
    "hireable": null,
    "bio": "Desarrollador de Aplicaciones Web y Mobile",
    "twitter_username": null,
    "public_repos": 4,
    "public_gists": 0,
    "followers": 0,
    "following": 2,
    "created_at": "2019-07-06T05:25:24Z",
    "updated_at": "2021-05-21T16:42:44Z"
  };